security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_TEACHER:     ROLE_USER
        ROLE_EDUCATOR:    ROLE_TEACHER
        ROLE_SUPER_ADMIN: ROLE_EDUCATOR
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
    access_control:
        - { path: ^/teacher, role: ROLE_TEACHER }
        - { path: ^/educator, role: ROLE_EDUCATOR }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }